--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    name: server
  name: server
  namespace: default  
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      name: server
  template: 
    metadata:  
      labels: 
        name: server
    spec: 
      containers: 
        - 
          image: "mariogrdn/discovery-server-df:def"
          name: server
      restartPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: server
  name: server-service
  namespace: default
spec: 
  ports: 
    - name: discovery
      port: 6000
      protocol: UDP
      targetPort: 6000
  selector: 
    name: server
