--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: server
  name: server-service
  namespace: default
spec: 
  ports: 
    - name: discovery
      port: 6000
      protocol: UDP
      targetPort: 6000
  selector: 
    name: server
